graph TD
    subgraph "Usuario"
        A[Usuario]
    end

    subgraph "Frontend (Dashboard)"
        B{Dashboard Web}
    end

    subgraph "Backend/API"
        E[API de Telemetria]
    end

    subgraph "Hardware"
        F[ESP32]
        I[FPGA Logica Fuzzy]
        G[Sensores]
        H[Atuadores]
    end

    subgraph "Servicos Externos"
        M[Firebase]
    end

    A -- "Acessa e Interage" --> B
    B -- "Busca/Envia Dados" --> E
    E -- "Recebe/Envia Dados" --> F
    F -- "Coleta Dados" --> G
    G -- "Envia Dados" --> F
    F -- "Envia Dados para Logica" --> I
    I -- "Controla" --> H
    H -- "Afeta" --> G
    E -- "Armazena/Autentica" --> M
    B -- "Autentica/Sincroniza" --> M

    style A fill:#fff,stroke:#333,stroke-width:2px,color:#000
    style B fill:#f9f,stroke:#333,stroke-width:2px,color:#000
    style E fill:#afa,stroke:#333,stroke-width:2px,color:#000
    style F fill:#ffc,stroke:#333,stroke-width:2px,color:#000
    style I fill:#cff,stroke:#333,stroke-width:2px,color:#000
    style G fill:#fcc,stroke:#333,stroke-width:2px,color:#000
    style H fill:#fcc,stroke:#333,stroke-width:2px,color:#000
    style M fill:#fcf,stroke:#333,stroke-width:2px,color:#000

    linkStyle 0 stroke:#f66,stroke-width:2px,fill:none;
    linkStyle 1 stroke:#66f,stroke-width:2px,fill:none;
    linkStyle 2 stroke:#6f6,stroke-width:2px,fill:none;
    linkStyle 3 stroke:#ff6,stroke-width:2px,fill:none;
    linkStyle 4 stroke:#ff6,stroke-width:2px,fill:none;
    linkStyle 5 stroke:#f6f,stroke-width:2px,fill:none;
    linkStyle 6 stroke:#6ff,stroke-width:2px,fill:none;
    linkStyle 7 stroke:#6ff,stroke-width:2px,fill:none;
    linkStyle 8 stroke:#fcf,stroke-width:2px,fill:none;
    linkStyle 9 stroke:#fcf,stroke:#333,stroke-width:2px,fill:none;

    classDef actor fill:#fff,stroke:#333,stroke-width:2px,color:#000;
    classDef frontend fill:#f9f,stroke:#333,stroke-width:2px,color:#000;
    classDef backend fill:#afa,stroke:#333,stroke-width:2px,color:#000;
    classDef hardware fill:#ffc,stroke:#333,stroke-width:2px,color:#000;
    classDef fuzzy_logic fill:#cff,stroke:#333,stroke-width:2px,color:#000;
    classDef sensors_actuators fill:#fcc,stroke:#333,stroke-width:2px,color:#000;
    classDef external_service fill:#fcf,stroke:#333,stroke-width:2px,color:#000;

    class A actor;
    class B frontend;
    class E backend;
    class F,I hardware;
    class G,H sensors_actuators;
    class M external_service;